### ISSUE TITLE
CardTable 与 RSet 的区别

### ISSUE THREAD

**Issue by fudali113** [chenghanpeng/jdk8u60#2]
看了书之后我感觉我还是比较难理解 卡表与记忆集之前的区别，按照我现在的理解，貌似他们都是为了方便不同记录不同分区之间的一些引用关系而存在的；

感觉他们都是在干着相同的事情，只是卡表记录着全部分块应用，Rset 只记录部分跨分区之间(老->新;老->老)的引用？

@chenghanpeng

**Comment by chenghanpeng** [comment]
不好意思，书中第四章有些可能介绍的不够清晰。 对G1来说RSet就是为了记录引用关系的。在书中有提到一个全局卡表，它的存在主要是为了记录每一个卡块（即512字节）中第一个对象所在的地址（在第五章的时，在介绍对象跨分区提到具体的使用）。
对于其他的垃圾回收器来说，CT有两个目的，第一是记录引用关系，第二是记录对象的修改（对象修改一般可以认为对象是活跃的，在垃圾回收过程需要被视作根-相当于引用，或者根据修改在垃圾回收过程中重新标记）。
由于G1中RSet的记录的Point in的引用，即别人指向了我，这就说可能有多个对象指向一个对象，卡表是没有办法记录这样的情况，所以采用了RSet的方式，RSet有3种实现，分别是稀疏，细粒度和粗粒度。这些都是为了保存别人对象指向当前分区对象。
对于G1来说，修改关系使用额外的一个队列管理（SATB），使用单独的线程并发的处理或者在GC时并行的处理（根据Queue的个数情况）。
