### ISSUE TITLE
堆内存为什么有慢速分配

### ISSUE THREAD

**Issue by lonelystone545** [chenghanpeng/jdk8u60#5]
我的理解是：因为tlab在E区有固定的占比，默认1%，那么当无法分配新的tlab时，会进入慢速分配，也就是直接在堆上分配。
那为什么不能调高tlab在E区的占比呢？尽可能的使用快速分配，避免慢速分配呢？这样设计可以么

**Comment by chenghanpeng** [comment]
TLAB的大小本来就可以直接设置（通过TLABSize），另外JVM还会根据运行的情况动态的调整TLAB的大小（resizeTLAB），但过大的TLAB可能对多线程不友好，有些线程分配速率很高（也就是更容易吃内存）会导致这类线程很快无法分配到空间，从而引发GC。使用中要注意平衡
