### ISSUE TITLE
《JVM G1源码分析与调优》 书中的异常

### ISSUE THREAD

**Issue by Berries-Wang** [chenghanpeng/jdk8u60#7]
《JVM G1源码分析与调优》 P86页，G1ConcRefinementThresholdStep 计算公式错误 ， 根据源码，应该是 _thread_threshold_step = (yellow_zone() - green_zone()) / (worker_thread_num() + 1); (少了个括号)

另 P143页下方“6.并发标记的正确性分析”  里面有一句话： “实际上存在Java根直接引用老生代对象，而不存在新生代对象到老生代的引用”  这句话是错误的吧，还是我理解有问题

望解答

**Comment by guizhou-feng** [comment]
@wangwei1996 问下这句话具体错在什么地方？

> 实际上存在Java根直接引用老生代对象，而不存在新生代对象到老生代的引用

**Comment by chenghanpeng** [comment]
不好意思，这句话可能系的不太清除。实际上此处想表达的是：如果存在Java直接引用到老生代对象（对象引用链路上的对象都不在Eden中），此时你会发现只使用Survivor作为并发标记的根是有问题的。所以对于这样的情况需要额外处理。
