### ISSUE TITLE
4.6 关于 G1RSetUpdatingPauseTimePercent 描述为GC完成时间的百分比（默认为10%）

### ISSUE THREAD

**Issue by guizhou-feng** [chenghanpeng/jdk8u60#8]
第4章， 4.6 介绍G1RSetUpdatingPauseTimePercent的原理时，提到"RSet所用的全部时间不超过GC完成时间的10%“
Oracle的文档有如下描述，大意是指G1RSetUpdatingPauseTimePercent 的分母为MaxGCPauseMillis而不是GC具体完成的时间
> G1 tries to schedule concurrent processing of the remembered set updates so that the Update RS phase takes approximately -XX:G1RSetUpdatingPauseTimePercent percent of the allowed maximum pause time. By decreasing this value, G1 usually performs more remembered set update work concurrently.

源码里面用了max_gc_time() 去乘这个G1RSetUpdatingPauseTimePercent，看起来符合上面文档的描述
https://github.com/chenghanpeng/jdk8u60/blob/7e3369b716de796aed802c314b9c23a5ec05325b/hotspot/src/share/vm/gc_implementation/g1/g1CollectorPolicy.cpp#L1187

所以想跟作者确认下这个细节的描述是否有不准确的地方 @chenghanpeng

**Comment by chenghanpeng** [comment]
是的，此处确实不够严谨。
