### ISSUE TITLE
4.2.1 请教Refinement采样线程采样不足的问题

### ISSUE THREAD

**Issue by guizhou-feng** [chenghanpeng/jdk8u60#9]
在第四章，4.2.1 书中介绍抽样线程时提到 G1ConcRefinementServiceIntervalMillis 可以控制采样的间隔时间

> 如果生产中发现采样不足可以减少该时间

这里想请教
1. 如何判断Refinement抽样不足？
2. 抽样不足对GC的影响怎么来进行评估？

缘由也是工作中遇到GC Predicted Pause Time会无故变高，Young Generation同时无故变少很多导致GC频繁，苦于没有好的方案
源码中发现Predicted Pause Time与rs_length相关，可以是没有相应日志可以判断变化的原因。

感谢作者的大作，受益许多

**Comment by chenghanpeng** [comment]
这个问题特别好。可以想象，如果该值过大，采样数据较少，由此可能造成预测不够准确，从而波动比较大。这个参数本质上是调整Eden的大小，也就是每间隔一定时间会重新采样GC的信息，然后更新Eden的大小。所以回到你的这个问题，如何判断采样是否合适？我的看法是Minor GC发生的频率是否合适以及每次Minor GC中Eden是否符合预期。
我个人会这样考虑这个参数，如果应用的分配速率（Allocation Speed）相对稳定，这个参数基本不用调整。但是如果应用的分配速率波动很大，也就说在某一个时刻会频繁触发GC，此时可以缩短该值，那么获得数据很多，预测Eden大小会更合适

**Comment by guizhou-feng** [comment]
感谢作者详细的解答，很有帮助
